// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkPpQ1vdjyT1Xpa1OuFJMzqaf0vFJ8pI',
    appId: '1:357691359563:web:2680d2eca2ccc58b3a68ce',
    messagingSenderId: '357691359563',
    projectId: 'rx100-login',
    authDomain: 'rx100-login.firebaseapp.com',
    storageBucket: 'rx100-login.appspot.com',
    measurementId: 'G-TC1T42FPGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6_cvNAYFtGqZ993pFOpqDXIioJ5-CkCY',
    appId: '1:357691359563:android:ed9727e1a5fdc64b3a68ce',
    messagingSenderId: '357691359563',
    projectId: 'rx100-login',
    storageBucket: 'rx100-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8cquGkZsTk1QPsW8GrETJeGGsxPi1jlg',
    appId: '1:357691359563:ios:36cae5cc124b44033a68ce',
    messagingSenderId: '357691359563',
    projectId: 'rx100-login',
    storageBucket: 'rx100-login.appspot.com',
    iosBundleId: 'com.example.tickett',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8cquGkZsTk1QPsW8GrETJeGGsxPi1jlg',
    appId: '1:357691359563:ios:36cae5cc124b44033a68ce',
    messagingSenderId: '357691359563',
    projectId: 'rx100-login',
    storageBucket: 'rx100-login.appspot.com',
    iosBundleId: 'com.example.tickett',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkkPpQ1vdjyT1Xpa1OuFJMzqaf0vFJ8pI',
    appId: '1:357691359563:web:2b2989b308d4b6233a68ce',
    messagingSenderId: '357691359563',
    projectId: 'rx100-login',
    authDomain: 'rx100-login.firebaseapp.com',
    storageBucket: 'rx100-login.appspot.com',
    measurementId: 'G-KPD3B1LTWJ',
  );
}
